export const hospitals = [
  {
    id: 1,
    name: "Bethlem Royal Hospital - Beckenham",
    street: "Monks Orchard Road",
    city: "Beckenham",
    postcode: "BR3 3BX",
  },
  {
    id: 2,
    name: "Bristol Royal Hospital for Children - Bristol",
    street: "Paul O'Gorman Building, Upper Maudlin Street",
    city: "Bristol",
    postcode: "BS2 8BJ",
  },
  {
    id: 3,
    name: "Bristol Royal Infirmary - Bristol",
    street: "Marlborough Street",
    city: "Bristol",
    postcode: "BS2 8HW",
  },
  {
    id: 4,
    name: "Central Middlesex Hospital - London",
    street: "Acton Lane",
    city: "Park Royal, London",
    postcode: "NW10 7NS",
  },
  {
    id: 5,
    name: "Chesterfield Royal Hospital - Chesterfield",
    street: "Calow",
    city: "Chesterfield",
    postcode: "S44 5BL",
  },
  {
    id: 6,
    name: "Cromwell Hospital – South Kensington (independent)",
    street: "164-178 Cromwell Road",
    city: "London",
    postcode: "SW5 0TU",
  },
  {
    id: 7,
    name: "Derbyshire Royal Infirmary - Derby",
    street: "London Road",
    city: "Derby",
    postcode: "DE1 2QY",
  },
  {
    id: 8,
    name: "Florence Nightingale Community Hospital - Derby",
    street: "London Road",
    city: "Derby",
    postcode: "DE1 2QY",
  },
  {
    id: 9,
    name: "Gloucestershire Royal Hospital - Gloucester",
    street: "Great Western Road",
    city: "Gloucester",
    postcode: "GL1 3NN",
  },
  {
    id: 10,
    name: "Leicester Royal Infirmary - Leicester",
    street: "Infirmary Square",
    city: "Leicester",
    postcode: "LE1 5WW",
  },
];

export const hospitalUnits = [
  {
    id: 1,
    hospitalId: 1,
    name: "Adult Critical Care",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 2,
    hospitalId: 2,
    name: "Adult Critical Care",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 3,
    hospitalId: 3,
    name: "Adult Critical Care",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 4,
    hospitalId: 4,
    name: "Critical Care Unit 1",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 5,
    hospitalId: 4,
    name: "Critical Care Unit 2",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 6,
    hospitalId: 4,
    name: "Critical Care Unit 3",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 7,
    hospitalId: 5,
    name: "Critical Care Unit 1",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 8,
    hospitalId: 5,
    name: "Critical Care Unit 2",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 9,
    hospitalId: 5,
    name: "Critical Care Unit 3",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 10,
    hospitalId: 6,
    name: "Critical Care Unit 1",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 11,
    hospitalId: 6,
    name: "Critical Care Unit 2",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 12,
    hospitalId: 6,
    name: "Critical Care Unit 3",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 13,
    hospitalId: 7,
    name: "Critical Care Unit 1",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 14,
    hospitalId: 7,
    name: "Critical Care Unit 2",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 15,
    hospitalId: 7,
    name: "Critical Care Unit 3",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 16,
    hospitalId: 8,
    name: "Critical Care Unit 1",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 17,
    hospitalId: 8,
    name: "Critical Care Unit 2",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 18,
    hospitalId: 8,
    name: "Critical Care Unit 3",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 19,
    hospitalId: 9,
    name: "Critical Care Unit 1",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 20,
    hospitalId: 9,
    name: "Critical Care Unit 2",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 21,
    hospitalId: 9,
    name: "Critical Care Unit 3",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 22,
    hospitalId: 10,
    name: "Critical Care Unit 1",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 23,
    hospitalId: 10,
    name: "Critical Care Unit 2",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
  {
    id: 24,
    hospitalId: 10,
    name: "Critical Care Unit 3",
    serviceCategory: "Critical Care",
    serviceType: "Intensive Care Unit",
  },
];
